# Generated by Django 5.0.2 on 2026-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160)),
                ('telephone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('with_guests', 'Attending with guests'), ('virtual', 'Not sure yet'), ('declined', 'Unable to attend')], max_length=20)),
                ('guest_count', models.PositiveSmallIntegerField(default=0)),
                ('attendee_type', models.CharField(blank=True, max_length=80)),
                ('dietary_requirements', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
